apiVersion: platform.mathumathiv.com/v1alpha1
kind: AppService
metadata:
  name: service-test
  namespace: example-demo
  labels:
    app.kubernetes.io/managed-by: backstage
  annotations:
    platform.mathumathiv.com/requested-by: unknown
    platform.mathumathiv.com/requested-at: '2026-07-31T18:51:16.013Z'
spec:
  image: nginx:1.27-alpine
  replicas: 2
  size: small
  environment: prod
  team: team-madhu
  costCentre: CC-1001
